### ISSUE TITLE
MovieWriter PillowWriter warning 

### ISSUE THREAD

**Issue by pmaxted** [pmaxted/pycheops#109]
dataset.animate_frames() produces the following warnings when running on a mac ...

MovieWriter PillowWriter unavailable; trying to use <class 'matplotlib.animation.PillowWriter'> instead.
MovieWriter PillowWriter warning safe to ignore.

**Comment by ThomasGWilson** [comment]
The first line:

MovieWriter PillowWriter unavailable; trying to use <class 'matplotlib.animation.PillowWriter'> instead.

is a warning from matplotlib, and also occurs on ubuntu. The second line:

 MovieWriter PillowWriter warning safe to ignore.

is a print statement I included to inform the users that the previous warning is safe to ignore. 

The first warning is known by the matplotlib team and is a bug in the calling of the warning rather than a class bug, and will apparently be resolved shortly. This is because the matplotlib animation call used in pycheops is already using the <class 'matplotlib.animation.PillowWriter'> argument.

**Comment by pmaxted** [comment]
Fixed in 0.7.8
