### ISSUE TITLE
dataset.diagnostic_plot  - no outlier rejection 

### ISSUE THREAD

**Issue by pmaxted** [pmaxted/pycheops#84]
Can we have a version of diagnostic_plot after outlier rejection?

**Comment by ThomasGWilson** [comment]
In pull request (#96 )

Updated dataset.diagnostic_plot to use values from dataset.lc therefore allowing users to create updated diagnostic plots after detrending and/or outlier clipping. Bottom right plot has been updated to included x and y centroid offsets rather than absolute values that can provide more information to the users about potential issues. "Bad" data flagged in the DRP can still be view by setting the flagged argument to True.
